// <auto-generated />
using System;
using System.Collections.Generic;
using System.Text.Json;
using Enerflow.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Enerflow.Infrastructure.Migrations
{
    [DbContext(typeof(EnerflowDbContext))]
    partial class EnerflowDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Enerflow.Domain.Entities.Compound", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<JsonDocument>("ConstantProperties")
                        .HasColumnType("jsonb");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("SimulationId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("SimulationId");

                    b.ToTable("Compounds");
                });

            modelBuilder.Entity("Enerflow.Domain.Entities.EnergyStream", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<double>("EnergyFlow")
                        .HasColumnType("double precision");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("SimulationId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("SimulationId");

                    b.ToTable("EnergyStreams");
                });

            modelBuilder.Entity("Enerflow.Domain.Entities.MaterialStream", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<double>("MassFlow")
                        .HasColumnType("double precision");

                    b.Property<Dictionary<string, double>>("MolarCompositions")
                        .IsRequired()
                        .HasColumnType("jsonb");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Phase")
                        .HasColumnType("text");

                    b.Property<double>("Pressure")
                        .HasColumnType("double precision");

                    b.Property<Guid>("SimulationId")
                        .HasColumnType("uuid");

                    b.Property<double>("Temperature")
                        .HasColumnType("double precision");

                    b.HasKey("Id");

                    b.HasIndex("SimulationId");

                    b.ToTable("MaterialStreams");
                });

            modelBuilder.Entity("Enerflow.Domain.Entities.Simulation", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("SystemOfUnits")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ThermoPackage")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.ToTable("Simulations");
                });

            modelBuilder.Entity("Enerflow.Domain.Entities.UnitOperation", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<JsonDocument>("ConfigParams")
                        .HasColumnType("jsonb");

                    b.PrimitiveCollection<List<Guid>>("InputStreamIds")
                        .IsRequired()
                        .HasColumnType("uuid[]");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.PrimitiveCollection<List<Guid>>("OutputStreamIds")
                        .IsRequired()
                        .HasColumnType("uuid[]");

                    b.Property<Guid>("SimulationId")
                        .HasColumnType("uuid");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("SimulationId");

                    b.ToTable("UnitOperations");
                });

            modelBuilder.Entity("Enerflow.Domain.Entities.Compound", b =>
                {
                    b.HasOne("Enerflow.Domain.Entities.Simulation", null)
                        .WithMany()
                        .HasForeignKey("SimulationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Enerflow.Domain.Entities.EnergyStream", b =>
                {
                    b.HasOne("Enerflow.Domain.Entities.Simulation", null)
                        .WithMany()
                        .HasForeignKey("SimulationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Enerflow.Domain.Entities.MaterialStream", b =>
                {
                    b.HasOne("Enerflow.Domain.Entities.Simulation", null)
                        .WithMany()
                        .HasForeignKey("SimulationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Enerflow.Domain.Entities.UnitOperation", b =>
                {
                    b.HasOne("Enerflow.Domain.Entities.Simulation", null)
                        .WithMany()
                        .HasForeignKey("SimulationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
